In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl           # 그래프를 그리는 패키지
import matplotlib.pyplot as plt    # 그래프를 그리는 패키지
from matplotlib import font_manager, rc
font_path = './malgun.ttf'
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)
plt.style.use('ggplot')

In [6]:
df = pd.read_csv('data/교통사고_날씨_습도_요일.csv',usecols=[2,3,4,5,6,7,9], encoding='cp949')
df

      발생지_시군구  total사고건수  평균기온  일강수량  평균상대습도  합계일조시간   날짜
0         강남구          7   3.5   0.0    75.9     1.7  공휴일
1         강동구          2   2.3   0.0    75.9     1.7  공휴일
2         강북구          2   3.8   0.0    75.9     1.7  공휴일
3         강서구          6   4.8   0.0    75.9     1.7  공휴일
4         관악구          2   3.5   0.0    75.9     1.7  공휴일
...       ...        ...   ...   ...     ...     ...  ...
26387     용산구          3  -7.2   0.0    39.3     9.1   평일
26388     은평구          2  -8.6   0.0    39.3     9.1   평일
26389     종로구          2   NaN   NaN     NaN     NaN   평일
26390      중구          3  -9.3   0.0    39.3     9.1   평일
26391     중랑구          5  -6.6   0.0    39.3     9.1   평일

[26392 rows x 7 columns]

In [11]:
df.isnull().sum() # 결측치 확인

발생지_시군구        0
total사고건수      0
평균기온         627
일강수량         413
평균상대습도       406
합계일조시간       648
날짜             0
dtype: int64

In [12]:
df1 = df.fillna(df.interpolate()) # 결측치 대체 앞뒤값의 평균값
df1

      발생지_시군구  total사고건수  평균기온  일강수량  평균상대습도  합계일조시간   날짜
0         강남구          7  3.50   0.0    75.9     1.7  공휴일
1         강동구          2  2.30   0.0    75.9     1.7  공휴일
2         강북구          2  3.80   0.0    75.9     1.7  공휴일
3         강서구          6  4.80   0.0    75.9     1.7  공휴일
4         관악구          2  3.50   0.0    75.9     1.7  공휴일
...       ...        ...   ...   ...     ...     ...  ...
26387     용산구          3 -7.20   0.0    39.3     9.1   평일
26388     은평구          2 -8.60   0.0    39.3     9.1   평일
26389     종로구          2 -8.95   0.0    39.3     9.1   평일
26390      중구          3 -9.30   0.0    39.3     9.1   평일
26391     중랑구          5 -6.60   0.0    39.3     9.1   평일

[26392 rows x 7 columns]

In [19]:
df2 = pd.get_dummies(df1)
df2

,total사고건수,평균기온,일강수량,평균상대습도,합계일조시간,발생지_시군구_강남구,발생지_시군구_강동구,발생지_시군구_강북구,발생지_시군구_강서구,발생지_시군구_관악구,...,발생지_시군구_양천구,발생지_시군구_영등포구,발생지_시군구_용산구,발생지_시군구_은평구,발생지_시군구_종로구,발생지_시군구_중구,발생지_시군구_중랑구,날짜_공휴일,날짜_주말,날짜_평일
0,7,3.50,0.0,75.9,1.7,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,2,2.30,0.0,75.9,1.7,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,2,3.80,0.0,75.9,1.7,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,6,4.80,0.0,75.9,1.7,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,2,3.50,0.0,75.9,1.7,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26387,3,-7.20,0.0,39.3,9.1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
26388,2,-8.60,0.0,39.3,9.1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
26389,2,-8.95,0.0,39.3,9.1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
26390,3,-9.30,0.0,39.3,9.1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
26391,5,-6.60,0.0,39.3,9.1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [37]:
df2.columns

Index(['total사고건수', '평균기온', '일강수량', '평균상대습도', '합계일조시간', '발생지_시군구_강남구',
       '발생지_시군구_강동구', '발생지_시군구_강북구', '발생지_시군구_강서구', '발생지_시군구_관악구',
       '발생지_시군구_광진구', '발생지_시군구_구로구', '발생지_시군구_금천구', '발생지_시군구_노원구',
       '발생지_시군구_도봉구', '발생지_시군구_동대문구', '발생지_시군구_동작구', '발생지_시군구_마포구',
       '발생지_시군구_서대문구', '발생지_시군구_서초구', '발생지_시군구_성동구', '발생지_시군구_성북구',
       '발생지_시군구_송파구', '발생지_시군구_양천구', '발생지_시군구_영등포구', '발생지_시군구_용산구',
       '발생지_시군구_은평구', '발생지_시군구_종로구', '발생지_시군구_중구', '발생지_시군구_중랑구', '날짜_공휴일',
       '날짜_주말', '날짜_평일'],
      dtype='object')

## StandardScaler

In [32]:
from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(df2)
df2_scaled = scaler.transform(df2) # numpy ndarry 반환

In [38]:
# numpy ndarry를 DataFrame으로 변환
df2_scaled = pd.DataFrame(data=df2_scaled, columns=df2.columns)

print('feature 들의 평균 값')
print(df2_scaled.mean())
print('\nfeature 들의 분산 값')
print(df2_scaled.var())

df2_scaled.head()
# 모든 컬럼 값의 평균이 0에 아주 가까운 값으로,
# 분산은 1에 아주 가까운 값으로 변환

feature 들의 평균 값
total사고건수      -1.253538e-15
평균기온           -1.509957e-15
일강수량           -4.074782e-15
평균상대습도          6.042285e-16
합계일조시간         -1.837934e-16
발생지_시군구_강남구     1.259833e-16
발생지_시군구_강동구    -5.385730e-16
발생지_시군구_강북구    -9.626953e-18
발생지_시군구_강서구     1.796877e-17
발생지_시군구_관악구     5.580772e-17
발생지_시군구_광진구     2.308807e-16
발생지_시군구_구로구     2.444914e-17
발생지_시군구_금천구     5.414735e-16
발생지_시군구_노원구    -7.311058e-16
발생지_시군구_도봉구    -2.799725e-16
발생지_시군구_동대문구    1.509562e-17
발생지_시군구_동작구     3.402140e-17
발생지_시군구_마포구     1.730433e-16
발생지_시군구_서대문구    2.511232e-16
발생지_시군구_서초구    -1.467790e-16
발생지_시군구_성동구     2.948473e-16
발생지_시군구_성북구     1.147431e-16
발생지_시군구_송파구     5.811297e-17
발생지_시군구_양천구     1.570579e-16
발생지_시군구_영등포구   -2.618649e-17
발생지_시군구_용산구    -3.265865e-16
발생지_시군구_은평구     1.268877e-16
발생지_시군구_종로구     1.524453e-16
발생지_시군구_중구     -6.860082e-16
발생지_시군구_중랑구    -6.168654e-17
날짜_공휴일          2.058462e-15
날짜_주말          -4.154923e-16
날짜_평일          -1.451224e-15
dtype: float64

feature 들의 분산 값
total사고건수       1.000038
평균기온            1.000038
일강수량            1.000038
평균상대습도          1.000038
합계일조시간          1.000038
발생지_시군구_강남구     1.000038
발생지_시군구_강동구     1.000038
발생지_시군구_강북구     1.000038
발생지_시군구_강서구     1.000038
발생지_시군구_관악구     1.000038
발생지_시군구_광진구     1.000038
발생지_시군구_구로구     1.000038
발생지_시군구_금천구     1.000038
발생지_시군구_노원구     1.000038
발생지_시군구_도봉구     1.000038
발생지_시군구_동대문구    1.000038
발생지_시군구_동작구     1.000038
발생지_시군구_마포구     1.000038
발생지_시군구_서대문구    1.000038
발생지_시군구_서초구     1.000038
발생지_시군구_성동구     1.000038
발생지_시군구_성북구     1.000038
발생지_시군구_송파구     1.000038
발생지_시군구_양천구     1.000038
발생지_시군구_영등포구    1.000038
발생지_시군구_용산구     1.000038
발생지_시군구_은평구     1.000038
발생지_시군구_종로구     1.000038
발생지_시군구_중구      1.000038
발생지_시군구_중랑구     1.000038
날짜_공휴일          1.000038
날짜_주말           1.000038
날짜_평일           1.000038
dtype: float64

,total사고건수,평균기온,일강수량,평균상대습도,합계일조시간,발생지_시군구_강남구,발생지_시군구_강동구,발생지_시군구_강북구,발생지_시군구_강서구,발생지_시군구_관악구,...,발생지_시군구_양천구,발생지_시군구_영등포구,발생지_시군구_용산구,발생지_시군구_은평구,발생지_시군구_종로구,발생지_시군구_중구,발생지_시군구_중랑구,날짜_공휴일,날짜_주말,날짜_평일
0,0.941349,-0.915086,-0.255501,1.237866,-1.371732,4.808775,-0.204458,-0.204358,-0.206561,-0.204760,...,-0.204358,-0.207755,-0.204156,-0.20254,-0.201626,-0.20081,-0.206561,4.597928,-0.614957,-1.459191
1,-0.883650,-1.027508,-0.255501,1.237866,-1.371732,-0.207953,4.890974,-0.204358,-0.206561,-0.204760,...,-0.204358,-0.207755,-0.204156,-0.20254,-0.201626,-0.20081,-0.206561,4.597928,-0.614957,-1.459191
2,-0.883650,-0.886981,-0.255501,1.237866,-1.371732,-0.207953,-0.204458,4.893381,-0.206561,-0.204760,...,-0.204358,-0.207755,-0.204156,-0.20254,-0.201626,-0.20081,-0.206561,4.597928,-0.614957,-1.459191
3,0.576349,-0.793296,-0.255501,1.237866,-1.371732,-0.207953,-0.204458,-0.204358,4.841181,-0.204760,...,-0.204358,-0.207755,-0.204156,-0.20254,-0.201626,-0.20081,-0.206561,4.597928,-0.614957,-1.459191
4,-0.883650,-0.915086,-0.255501,1.237866,-1.371732,-0.207953,-0.204458,-0.204358,-0.206561,4.883772,...,-0.204358,-0.207755,-0.204156,-0.20254,-0.201626,-0.20081,-0.206561,4.597928,-0.614957,-1.459191

In [40]:
df2.to_csv("C:/PythonStudy/프로젝트/data/row.csv", encoding='utf-8',index=False)
df2_scaled.to_csv("C:/PythonStudy/프로젝트/data/row_scaled.csv", encoding='utf-8',index=False)